FROM <%= @image %>
RUN echo hello world
RUN [ ! -f "/sbin/initctl" ] || dpkg-divert --local --rename --add /sbin/initctl && ln -sf /bin/true /sbin/initctl
ENV DEBIAN_FRONTEND noninteractive
ENV container docker
RUN apt-get update
RUN apt-get install -y sudo openssh-server curl lsb-release ansible python3-toml
RUN if ! getent passwd kitchen; then \
  useradd -d /home/kitchen -m -s /bin/bash -p '*' kitchen; \
  fi
RUN echo "kitchen ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers.d/kitchen
RUN echo "Defaults !requiretty" >> /etc/sudoers.d/kitchen
RUN mkdir -p /home/kitchen/.ssh
RUN chown -R kitchen /home/kitchen/.ssh
RUN chmod 0700 /home/kitchen/.ssh
RUN touch /home/kitchen/.ssh/authorized_keys
RUN chown kitchen /home/kitchen/.ssh/authorized_keys
RUN chmod 0600 /home/kitchen/.ssh/authorized_keys
RUN mkdir -p /run/sshd
RUN echo <%= File.read(@public_key) %> >> /home/kitchen/.ssh/authorized_keys
